
include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"

linter:
  rules:
    # ERRORS
    always_use_package_imports: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    # STYLE
    always_put_control_body_on_new_line: true
    avoid_catching_errors: true
    avoid_escaping_inner_quotes: true
    avoid_field_initializers_in_const_classes: true
    combinators_ordering: true
    eol_at_end_of_file: true
    join_return_with_assignment: true
    noop_primitive_operations: true
    parameter_assignments: true
    prefer_expression_function_bodies: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_foreach: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_int_literals: true
    prefer_mixin: true
    prefer_null_aware_method_calls: true
    require_trailing_commas: true
    sort_pub_dependencies: true
    sort_unnamed_constructors_first: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_to_list_in_spreads: true
    use_colored_box: true
    use_decorated_box: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true
    use_raw_strings: true