name: nekodroid
description: Unofficial android client for neko-sama.fr.
version: 0.0.1+1
homepage: https://github.com/zkayia/nekodroid
issue_tracker: https://github.com/zkayia/nekodroid/issues
repository: https://github.com/zkayia/nekodroid


publish_to: none


environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  after_layout: ^1.2.0
  cached_network_image: ^3.4.1
  collection: ^1.18.0
  connectivity_plus: ^6.0.5
  cupertino_icons: ^1.0.6
  drift: ^2.20.0
  equatable: ^2.0.5
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  fluttertoast: ^8.2.8
  go_router: ^14.2.3
  material_symbols_icons: ^4.2780.0
  nekosama:
    path: C:/Users/Zak/Documents/Dev/code/dart/nekosama_dart
  package_info_plus: ^8.0.1
  path: ^1.9.0
  path_provider: ^2.1.4
  riverpod_annotation: ^2.3.5
  share_plus: ^10.0.0
  shared_preferences: ^2.3.2
  skeletonizer: ^1.4.2
  sqlite3: ^2.4.5
  sqlite3_flutter_libs: ^0.5.24
  url_launcher: ^6.3.0
  wakelock_plus: ^1.2.7


dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  device_preview: ^1.2.0
  drift_db_viewer: ^2.0.0
  drift_dev: ^2.20.1
  flutter_gen_runner: ^5.6.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13


flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/img/nekodroid_logo_margin.png"
  adaptive_icon_background: "#101010"
  adaptive_icon_foreground: "assets/img/nekodroid_logo_margin.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/img/nekodroid_splash_dark.png
  color_dark: "#101010"
  image_dark: assets/img/nekodroid_splash.png
  android_12:
    image: assets/img/nekodroid_splash_android12.png
    color: "#ffffff"
    icon_background_color: "#101010"
    image_dark: assets/img/nekodroid_splash_android12.png
    color_dark: "#101010"
    icon_background_color_dark: "#101010"

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/js/
  # fonts:
  #  - family: LetsIcons
  #    fonts:
  #     - asset: assets/fonts/lets_icons.ttf

# derry scripts
scripts:
  apk: flutter build apk --split-per-abi
  build: dart run build_runner build
  buildf: dart run build_runner build --delete-conflicting-outputs
  buildw: dart run build_runner watch
  splash: dart run flutter_native_splash:create
  icons: dart run flutter_launcher_icons
  clean:
    - flutter clean
    - flutter pub get
    - $buildf