name: nekodroid
description: Unofficial android client for neko-sama.fr.
version: 1.0.0+1
homepage: https://github.com/zkayia/nekodroid
issue_tracker: https://github.com/zkayia/nekodroid/issues
repository: https://github.com/zkayia/nekodroid


publish_to: none


environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  after_layout: ^1.2.0
  android_intent_plus: ^3.1.5
  async: ^2.9.0
  boxicons:
    git:
      url: https://github.com/zkayia/dartpacks
      path: boxicons
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.7.2+3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.1.1
  flutter_svg: ^1.1.6
  fluttertoast: ^8.1.2
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  nekosama:
    git:
      url: https://github.com/zkayia/nekosama_dart
      path: packages/nekosama
  package_info_plus: ^3.0.2
  path_provider: ^2.0.11
  share_plus: ^6.3.0
  video_player: ^2.4.10
  wakelock: ^0.6.2

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.3.0
  device_preview: ^1.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/nekodroid_logo_app.png"
  adaptive_icon_background: "#262626"
  adaptive_icon_foreground: "assets/images/nekodroid_logo_app.png"

flutter_native_splash:
  color: "#fafafa"
  image: assets/images/nekodroid_logo_black.png
  color_dark: "#171717"
  image_dark: assets/images/nekodroid_logo_regular.png

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/player/
    - assets/images/

# derry scripts
scripts:
  apk: flutter build apk --split-per-abi
  build: flutter pub run build_runner build
  buildw: flutter pub run build_runner watch
  buildf: flutter pub run build_runner build --delete-conflicting-outputs
  unused:
    - flutter pub run dart_code_metrics:metrics check-unused-code lib
    - flutter pub run dart_code_metrics:metrics check-unused-files lib
  clean:
    - flutter clean
    - flutter pub get
    - $buildf
    