name: nekodroid
description: Unofficial android client for neko-sama.fr.
version: 1.0.0+1
homepage: https://github.com/zkayia/nekodroid
issue_tracker: https://github.com/zkayia/nekodroid/issues
repository: https://github.com/zkayia/nekodroid


publish_to: none


environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  android_intent_plus: ^3.1.1
  boxicons:
    git:
      url: https://github.com/zkayia/dartpacks
      path: boxicons
  cached_network_image: ^3.2.1
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.4.1+1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  isar: ^3.0.0-dev.13
  isar_flutter_libs: ^3.0.0-dev.13
  lazy_load_scrollview: ^1.3.0
  nekosama:
    git:
      url: https://github.com/zkayia/nekosama_dart
      path: packages/nekosama
  package_info_plus: ^1.4.2
  path_provider: ^2.0.11
  share_plus: ^4.0.4
  video_player: ^2.4.5

dev_dependencies:
  build_runner: ^2.2.0
  dart_code_metrics: ^4.15.2
  device_preview: ^1.1.0
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.1.6
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.0-dev.13

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/nekodroid_logo_app.png"
  adaptive_icon_background: "#262626"
  adaptive_icon_foreground: "assets/images/nekodroid_logo_app.png"

flutter_native_splash:
  color: "#fafafa"
  image: assets/images/nekodroid_logo_black.png
  color_dark: "#171717"
  image_dark: assets/images/nekodroid_logo_regular.png

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/player/
    - assets/images/